from __future__ import annotations

import hashlib
import json
from datetime import datetime, timezone
from typing import Any

from app.db.session import get_connection, init_db
from app.services import rendering_service, registry_service


def _next_job_id() -> str:
    init_db()
    with get_connection() as connection:
        row = connection.execute("SELECT COUNT(*) AS count FROM generation_jobs").fetchone()
    return f"job.{row['count'] + 1:08d}"


def _job_payload(unit_id: str, layer: str, style_profile: str) -> dict[str, Any]:
    unit = registry_service.load_unit(unit_id)
    locked_inputs = {
        "hebrew_tokens": unit.get("tokens", []),
    }
    for rendering in unit.get("renderings", []):
        if rendering["layer"] in {"gloss", "literal", "concept"} and rendering["status"] == "canonical":
            locked_inputs[f"{rendering['layer']}_rendering_id"] = rendering["rendering_id"]
    return {
        "unit_id": unit_id,
        "layer": layer,
        "locked_inputs": locked_inputs,
        "style_profile": next(
            item
            for item in registry_service.load_project().get("style_profiles", [])
            if item["style_profile_id"] == style_profile
        ),
    }


def _candidate_text(unit: dict[str, Any], layer: str) -> str:
    literal = next((item["text"] for item in unit.get("renderings", []) if item["layer"] == "literal"), unit["source_transliteration"])
    if layer == "gloss":
        return literal
    if layer == "phrase":
        return literal.replace(" are ", " ").replace(" is ", " ")
    if layer == "concept":
        return literal + " — concept layer"
    if layer in {"lyric", "metered_lyric", "parallelism_lyric"}:
        return literal + " in song"
    return literal


def generate_for_unit(unit_id: str, layer: str, style_profile: str = "study_literal") -> dict[str, Any]:
    init_db()
    payload = _job_payload(unit_id, layer, style_profile)
    payload_bytes = json.dumps(payload, sort_keys=True, ensure_ascii=False).encode("utf-8")
    input_hash = hashlib.sha256(payload_bytes).hexdigest()
    job_id = _next_job_id()
    unit = registry_service.load_unit(unit_id)
    candidate_text = _candidate_text(unit, layer)
    created = rendering_service.create_rendering(
        unit_id=unit_id,
        layer=layer,
        text=candidate_text,
        status="proposed",
        rationale=f"Generated by local deterministic adapter with profile {style_profile}",
        created_by="generation-service",
        style_tags=[layer, style_profile],
    )
    result = {
        "job_id": job_id,
        "unit_id": unit_id,
        "layer": layer,
        "status": "completed",
        "input_hash": input_hash,
        "model_profile": style_profile,
        "prompt_version": "v1-fixture",
        "seed": 42,
        "runtime_metadata": {"completed_at": datetime.now(timezone.utc).isoformat()},
        "output": {
            "unit_id": unit_id,
            "layer": layer,
            "candidates": [
                {
                    "text": created["text"],
                    "rationale": created["rationale"],
                    "alignment_hints": [],
                    "drift_flags": created["drift_flags"],
                    "metrics": created["metrics"],
                }
            ],
        },
    }
    with get_connection() as connection:
        connection.execute(
            "INSERT INTO generation_jobs(job_id, unit_id, layer, status, input_hash, model_profile, prompt_version, seed, runtime_metadata) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)",
            (
                result["job_id"],
                result["unit_id"],
                result["layer"],
                result["status"],
                result["input_hash"],
                result["model_profile"],
                result["prompt_version"],
                result["seed"],
                json.dumps(result["runtime_metadata"]),
            ),
        )
    return result


def generate_for_psalm(psalm_id: str, layer: str, style_profile: str = "study_literal") -> list[dict[str, Any]]:
    psalm = registry_service.load_psalm(psalm_id)
    return [generate_for_unit(unit["unit_id"], layer=layer, style_profile=style_profile) for unit in psalm["units"]]


def get_job(job_id: str) -> dict[str, Any]:
    with get_connection() as connection:
        row = connection.execute("SELECT * FROM generation_jobs WHERE job_id = ?", (job_id,)).fetchone()
    if row is None:
        raise KeyError(job_id)
    return dict(row)


def rerun_layer(unit_id: str, layer: str) -> dict[str, Any]:
    return generate_for_unit(unit_id=unit_id, layer=layer)
