"""Build (or verify) the committed psalm versification table.

Two independent facts per psalm:

* ``display_verse_offset`` -- how many MT verses the superscription consumes,
  so English display numbering can be derived from the Masoretic numbering the
  corpus stores. This is DERIVED, not asserted: it is the MT verse count minus
  the verse count of the vendored public-domain English witness, which folds the
  superscription into an unnumbered heading. Every psalm lands on 0, 1 or 2,
  which is what the superscription convention predicts.

* ``septuagint`` / ``vulgate`` -- the canonical Greek and Latin numbering, which
  diverges from the Masoretic sequence because the LXX joins MT 9-10 and MT
  114-115, and splits MT 116 and MT 147. This is a fixed, well-attested range
  mapping, encoded below rather than recalled per psalm.

Run with --check in tests or CI to assert the committed table still matches the
corpus.
"""

from __future__ import annotations

import argparse
import collections
import json
import sys
from pathlib import Path
from typing import Any

ROOT = Path(__file__).resolve().parents[1]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

from app.core.config import get_settings  # noqa: E402
from app.services import registry_service  # noqa: E402

WITNESS_SOURCE = "web"

#: Masoretic -> Septuagint/Vulgate psalm numbering. Each entry maps an inclusive
#: MT range to the Greek number(s) covering it.
_MT_TO_GREEK: tuple[tuple[int, int, tuple[int, ...]], ...] = (
    (1, 8, ()),  # identical; resolved per-number
    (9, 10, (9,)),  # MT 9 and 10 are a single Greek psalm 9
    (11, 113, ()),  # offset by one
    (114, 115, (113,)),  # joined
    (116, 116, (114, 115)),  # split
    (117, 146, ()),  # offset by one
    (147, 147, (146, 147)),  # split
    (148, 150, ()),  # identical
)


def greek_numbers(mt: int) -> list[int]:
    """Septuagint/Vulgate number(s) for a Masoretic psalm number."""
    for low, high, fixed in _MT_TO_GREEK:
        if low <= mt <= high:
            if fixed:
                return list(fixed)
            # The identical and offset-by-one bands.
            return [mt] if high <= 8 or low >= 148 else [mt - 1]
    raise ValueError(f"Psalm number out of range: {mt}")


def english_verse_counts() -> dict[int, int]:
    counts: collections.Counter[int] = collections.Counter()
    for chapter, _verse in registry_service._load_public_domain_witness_map(WITNESS_SOURCE):
        counts[chapter] += 1
    return dict(counts)


def build_table() -> dict[str, Any]:
    counts = english_verse_counts()
    psalms: dict[str, Any] = {}
    for psalm_id in registry_service.list_psalm_ids():
        mt_number = int(psalm_id[2:])
        mt_verses = len(registry_service.load_psalm_meta(psalm_id).get("unit_ids", []))
        english_verses = counts.get(mt_number)
        if not english_verses:
            continue
        offset = mt_verses - english_verses
        if offset not in (0, 1, 2):
            raise ValueError(
                f"{psalm_id}: implausible display_verse_offset {offset} "
                f"(MT {mt_verses} verses, English {english_verses})"
            )
        greek = greek_numbers(mt_number)
        psalms[psalm_id] = {
            "mt": mt_number,
            "septuagint": greek,
            "vulgate": greek,
            "mt_verses": mt_verses,
            "english_verses": english_verses,
            "display_verse_offset": offset,
        }
    return {
        "note": (
            "Generated by scripts/build_versification.py. display_verse_offset is derived "
            "from the vendored public-domain English witness, not asserted. Regenerate with "
            "that script; verify with --check."
        ),
        "witness_source": WITNESS_SOURCE,
        "psalms": psalms,
    }


def table_path() -> Path:
    return get_settings().content_dir / "versification.json"


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true", help="verify without writing")
    args = parser.parse_args()

    table = build_table()
    path = table_path()

    if args.check:
        if not path.exists():
            print(f"missing {path}", file=sys.stderr)
            return 1
        current = json.loads(path.read_text(encoding="utf-8"))
        if current.get("psalms") != table["psalms"]:
            print("versification table is stale; rerun without --check", file=sys.stderr)
            return 1
        print(f"versification OK: {len(table['psalms'])} psalms")
        return 0

    registry_service.write_json(path, table)
    offsets = collections.Counter(p["display_verse_offset"] for p in table["psalms"].values())
    print(f"wrote {path} ({len(table['psalms'])} psalms)")
    print("offset distribution:", dict(sorted(offsets.items())))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
